### ISSUE TITLE
Handled in one USRP

### ISSUE THREAD

**Issue by yerongchagui** [kit-cel/gr-radar#19]
Hi guys，As far as I know, It is necessary to have TWO USRP N210s to implement radar applications in terms of transmit and receive, I have a USRP X310 with two channels, which means I can handle these just in ONE USRP. My question is: is it possible to run gr-radar examples on USRP X310 without any code modifications , or I should modify the code. if so, how to modify it? Thanks

**Comment by sbmueller** [comment]
That's actually a thing I wanted to try for a long time. Cool that you are interested in that, too! From my perspective it should theoretically work (you just have to set the correct subdevices in the GR blocks for the two channels). Practically I wouldn't expect superior results because of stronger crosstalk. Out of interest: what antennas are you planning to use?

**Comment by h57jafari** [comment]
if want to use only one USRP X410. how I can define TX and RX channels in "USRP echotimer". as USRP X410 have 4 TX and 4 RX channels. what parameters inside "USRP echotimer" need to be set and to what values.
