### ISSUE TITLE
Clarification of specs

### ISSUE THREAD

**Issue by raidfire99** [kit-cel/gr-radar#34]
Hi I'm a non UHD owner, i use an adalam pluto, i would like a little clarification as to if the blocks other than echo timer will run without a uhd device, done several installs accross several flavours of linux but all usage of gr-radar blocks seem to spawn the error below, suggesting each block is checking for the uhd hardware, good example is the fsk gen block. i have qt4, qwt6, matlibplot, as current versions but still cannot get any block to run.

current attempt ubuntu 18 virtual box, gnuradio dev installed with apt-get as is gr-radar.

If im wasting my time trying to get this to run please say so if I'm doing something stupid please shout me out and point me in the right direction.

Basic test fsk sig gen ->null sink
Boost_106501; UHD_003.010.003.000-0-unknown
>>> Done (return code -11

**Comment by raidfire99** [comment]
I got around my UHD issues with a pyboms install of gnuradio building the uhd module from source, which now leads me to the question:
Whats inside the echo timer, is it a simple rx/tx component for the usrp or is there some other processing going on under the hood, I tried to replace the echotimer with pluto sources and sinks but the scatter plots are showing very random results which leads me to think there is something between the rx and tx in the echo timer, if this is the case can you point me in the right direction for the code and i will attempt to build a pluto echotimer.

**Comment by dkozel** [comment]
@raidfire99 The echo timer block does specific time aligning operations which are only supported in the USRP. I don't know if the Pluto supports time aligning TX and RX so can't point you towards a good starting place.

Did you continue to work on this?

**Comment by raidfire99** [comment]
Parked the project over the summer, new dev computer build out etc just getting back into it, now i know what the echotimer is doing i can 
1. Check with the guys at analog devices on the hardware specifics, they have an excellent response time.
2. Keep pushing with another idea taken from a USRP radar paper, the pluto like the usrp has 2x rx, tx, you can talk to both but only 1 pair is connected to sma, the other pair can be accessed by a gpio inside the pluto, build a 50 ohm feedback loop accross the redundant pair as a timing reference.

**Comment by chrisjohgorman** [comment]
Hello @dkozel and @raidfire99,

I am also a pluto user and wondered about usrp_echotimer_cc_impl.cc.  I simply commented out the entire file in order to build gr-radar.  I had to do a few other modifications in order to build, but got it installed in gnuradio 3.8.1. 

I have looked around and Srikanth Pagadarai's work on enabling precise timing control in SDRs seems like a good place to start trying to replace the functionality of usrp_echotimer_cc_impl.cc for the pluto.  Unfortunately for me his lecture at grcon19 went over my head.  For those who have more experience in this area than I do, his lecture can be found at https://www.youtube.com/watch?v=FcpM6vGroUk .  

I will send off an email, once I figure out how, on analog devices web page and see what they say about implementing precise timing on the pluto.  

Thanks
Chris
