### ISSUE TITLE
Synchronisation of usrp n210 and usrp x300

### ISSUE THREAD

**Issue by bluelightvision** [kit-cel/gr-radar#8]
Hi, I have an application of radar and I have two usrp ; one n210 and the other x300.
Can we make them synchronised ?

**Comment by stwunsch** [comment]
Hi,

Unfortunately I suppose this is not possible yet. The problem is the x300, because you need to specify the subdevice specs for this USRP and this is not implemented. But just try it, probably it is working with the default subdevice specs. And as far as I know the x300 doesn't have a MIMO port (for a MIMO cable). If this is true, you have to use GPSDO for the time sync!

There is some code on the branch echotimer_new. This echotimer version solves all of this problems, but unfortunately it seems to be buggy on the receive stream. If you are motivated and skilled enough, you can try to fix it.

Best regards

**Comment by bluelightvision** [comment]
Hi stwunsch 

I'll try to use the GPSDO because as you said there is no MIMO port for the x300.
Thank you.
